In [2]:
cd /data/store01/data_dirs/students/ucfafyi/S2_MODIS

/data/store01/data_dirs/students/ucfafyi/S2_MODIS


In [3]:
import sys
sys.path.insert(0, 'python')
from fastRWpkl import *
import glob
import numpy as np

In [4]:
pkls = glob.glob('pkls/50*PSF*00.pkl')

In [5]:
fnames = [j.split('/')[1] for j in (i.split('00.')[0] for i in pkls)]

In [6]:
c = []
for fname in sorted(fnames):
    data = np.array([np.hstack((i[0], np.array(i[1]))) for i in parallel_rw_pkl(None, fname, 'r')[0]])
    mi = data[data[:,5] == data[:,5].min()]
    c.append([fname, mi])

In [8]:
len(c[:-5])

17

In [9]:
fnames

['50SKG_0503_PSF.pkl',
 '50SKG_0513_PSF.pkl',
 '50SKG_0526_PSF.pkl',
 '50SKG_0117_PSF.pkl',
 '50SKG_0124_PSF.pkl',
 '50SKG_0203_PSF.pkl',
 '50SKG_0216_PSF.pkl',
 '50SKG_0413_PSF.pkl',
 '50SKG_0612_PSF.pkl',
 '50SKG_0615_PSF.pkl',
 '50SKG_0622_PSF.pkl',
 '50SKG_0725_PSF.pkl',
 '50SKG_0811_PSF.pkl',
 '50SKG_0814_PSF.pkl',
 '50SPG_1014_PSF.pkl',
 '50SPG_1004_PSF.pkl',
 '50SPG_0616_PSF.pkl',
 '50SPG_0530_PSF.pkl',
 '50SPG_0510_PSF.pkl',
 '50SPG_0430_PSF.pkl',
 '50SNG_0828_PSF.pkl',
 '50SNG_0530_PSF.pkl']

In [10]:
sorted(fnames)[:-5]

['50SKG_0117_PSF.pkl',
 '50SKG_0124_PSF.pkl',
 '50SKG_0203_PSF.pkl',
 '50SKG_0216_PSF.pkl',
 '50SKG_0413_PSF.pkl',
 '50SKG_0503_PSF.pkl',
 '50SKG_0513_PSF.pkl',
 '50SKG_0526_PSF.pkl',
 '50SKG_0612_PSF.pkl',
 '50SKG_0615_PSF.pkl',
 '50SKG_0622_PSF.pkl',
 '50SKG_0725_PSF.pkl',
 '50SKG_0811_PSF.pkl',
 '50SKG_0814_PSF.pkl',
 '50SNG_0530_PSF.pkl',
 '50SNG_0828_PSF.pkl',
 '50SPG_0430_PSF.pkl']

In [11]:
paras = [[i[0],i[1].flatten()] for i in  c[:-5] if i[1].flatten()[-1]<0.1]

In [12]:
paras

[['50SKG_0413_PSF.pkl',
  array([  2.92344905e+01,   4.31667817e+01,  -1.23489766e+01,
           3.07690430e+01,   1.06054688e+01,   1.75041610e-02])],
 ['50SKG_0503_PSF.pkl',
  array([  3.04870426e+01,   4.13286710e+01,  -1.35535958e+01,
           2.61445312e+01,   1.03125000e+00,   1.37596719e-02])],
 ['50SKG_0513_PSF.pkl',
  array([  2.97274187e+01,   4.02140327e+01,  -1.14484172e+01,
           2.39062500e+01,   6.37500000e+00,   3.24080654e-02])],
 ['50SKG_0612_PSF.pkl',
  array([  4.06099755e+01,   5.22830076e+01,   1.17524859e+01,
           2.25468750e+01,   3.37500000e+00,   3.43395558e-02])],
 ['50SKG_0622_PSF.pkl',
  array([  2.69970497e+01,   4.49402981e+01,  -7.21792374e+00,
           2.20356445e+01,   1.10156250e+00,   1.06793924e-02])],
 ['50SNG_0530_PSF.pkl',
  array([  2.81029865e+01,   4.04234524e+01,  -4.34902714e+00,
           2.00625000e+01,   9.00000000e+00,   3.24066091e-02])],
 ['50SNG_0828_PSF.pkl',
  array([ 30.89561813,  41.29100136, -15.        ,  20.121